web:
    image: leowgweb/nginx-php-7.0
    restart: always
    container_name: nginx-php-7.0
    ports:
        - "80:80" # web
        - "2221:22" # ssh
        - "35729:35729" # live reload
        - "9876:9876" # karma server
    volumes:
        - ~/.composer:/home/homestead/.composer # composer caching
        - ~/.gitconfig:/home/homestead/.gitconfig # Git configuration ( access alias && config )
        - ~/.ssh:/home/homestead/.ssh # Ssh keys for easy deployment inside the container
        - ~/apps/nginx-php-7.0/www:/apps/www # all apps
        - ~/apps/nginx-php-7.0/volumes/nginx/sites-available:/etc/nginx/sites-available # nginx sites ( in case you recreate the container )
        - ~/apps/nginx-php-7.0/volumes/nginx/sites-enabled:/etc/nginx/sites-enabled # nginx sites ( in case you recreate the container )
        - ~/apps/nginx-php-7.0/volumes/nginx/php:/etc/php/7.0/fpm
    links:
        - mysql

web2:
    image: leowgweb/apache-php-7.1
    restart: always
    container_name: apache-php-7.1
    ports:
        - "8000:80"
        - "2222:22"
    volumes:
        - ~/.composer:/home/homestead/.composer
        - ~/.gitconfig:/home/homestead/.gitconfig
        - ~/.ssh:/home/homestead/.ssh
        - ~/apps/apache-php-7.1/www:/apps/www
        - ~/apps/apache-php-7.1/volumes/apache/sites-available:/etc/apache2/sites-available
        - ~/apps/apache-php-7.1/volumes/apache/sites-enabled:/etc/apache2/sites-enabled
        - ~/apps/apache-php-7.1/volumes/apache/php/:/usr/local/etc/php
    links:
        - mysql

web3:
    image: leowgweb/nginx-php-5.6
    restart: always
    container_name: nginx-php-5.6
    ports:
        - "8001:80"
        - "2223:22"
    volumes:
        - ~/.composer:/home/homestead/.composer # composer caching
        - ~/.gitconfig:/home/homestead/.gitconfig # Git configuration ( access alias && config )
        - ~/.ssh:/home/homestead/.ssh # Ssh keys for easy deployment inside the container
        - ~/apps/nginx-php-5.6/www:/apps/www # all apps
        - ~/apps/nginx-php-5.6/volumes/nginx/sites-available:/etc/nginx/sites-available # nginx sites ( in case you recreate the container )
        - ~/apps/nginx-php-5.6/volumes/nginx/sites-enabled:/etc/nginx/sites-enabled # nginx sites ( in case you recreate the container )
        - ~/apps/nginx-php-5.6/volumes/nginx/php:/etc/php5/fpm
    links:
        - mysql

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin
    links:
        - mysql
    ports:
        - "8080:80"
    environment:
        PMA_HOST: mysql
        MYSQL_USERNAME: "root"
        MYSQL_ROOT_PASSWORD: "root"

mysql:
    image: mysql
    restart: always
    container_name: mysql
    ports:
        - "33060:3306"
    environment:
        MYSQL_ROOT_PASSWORD: "root"
    volumes:
        - ~/apps/mysql:/var/lib/mysql # database files
